"""version 8

Revision ID: 0a38d2ccd074
Revises: 926c0848c4f0
Create Date: 2021-02-08 08:10:10.026707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a38d2ccd074'
down_revision = '926c0848c4f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
