"""version 10

Revision ID: 29b267ef41a0
Revises: 8f5a28c813ec
Create Date: 2021-02-08 08:17:48.430944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29b267ef41a0'
down_revision = '8f5a28c813ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diecuts', sa.Column('descript', sa.String(length=255), nullable=True))
    op.add_column('diecuts', sa.Column('pict', sa.String(length=255), nullable=True))
    op.drop_column('diecuts', 'descriptions')
    op.drop_column('diecuts', 'img')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diecuts', sa.Column('img', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True))
    op.add_column('diecuts', sa.Column('descriptions', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('diecuts', 'pict')
    op.drop_column('diecuts', 'descript')
    # ### end Alembic commands ###
