"""version 21

Revision ID: 4174b6f21331
Revises: aa28016578fa
Create Date: 2021-03-04 16:05:56.344084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4174b6f21331'
down_revision = 'aa28016578fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
