"""version 21

Revision ID: 770e9bcaec52
Revises: 885fe2960e21
Create Date: 2021-03-04 11:43:03.044573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '770e9bcaec52'
down_revision = '885fe2960e21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
