"""version 21

Revision ID: 885fe2960e21
Revises: bb4ec18efd1d
Create Date: 2021-03-04 10:21:43.066213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '885fe2960e21'
down_revision = 'bb4ec18efd1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
