"""version 7

Revision ID: 926c0848c4f0
Revises: 7b4d2603510e
Create Date: 2021-02-05 23:41:33.813439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '926c0848c4f0'
down_revision = '7b4d2603510e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
