"""version 12

Revision ID: 926cab5a55e2
Revises: db131287c30e
Create Date: 2021-02-08 09:34:50.887154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '926cab5a55e2'
down_revision = 'db131287c30e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diecuts', 'col_test1')
    op.drop_column('diecuts', 'col_test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diecuts', sa.Column('col_test', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('diecuts', sa.Column('col_test1', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
