"""version 5

Revision ID: 9c108cb41ea2
Revises: aa30e1f30450
Create Date: 2021-02-04 14:36:37.600224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c108cb41ea2'
down_revision = 'aa30e1f30450'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
