"""version 15

Revision ID: a8c071ab6076
Revises: daa6a6107e43
Create Date: 2021-02-15 10:35:37.578144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8c071ab6076'
down_revision = 'daa6a6107e43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diecuts', sa.Column('version_uuid', sa.String(length=32), nullable=True))
    op.add_column('zubs', sa.Column('version_uuid', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zubs', 'version_uuid')
    op.drop_column('diecuts', 'version_uuid')
    # ### end Alembic commands ###
