"""version 21

Revision ID: aa28016578fa
Revises: df4caffb8bbf
Create Date: 2021-03-04 16:04:46.199250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa28016578fa'
down_revision = 'df4caffb8bbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
