"""version 13

Revision ID: b81465f8e210
Revises: d1d3a355711b
Create Date: 2021-02-08 09:38:32.074611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b81465f8e210'
down_revision = 'd1d3a355711b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
