"""version 21

Revision ID: bb96342dcba7
Revises: b15baf06017b
Create Date: 2021-03-04 14:33:56.737218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb96342dcba7'
down_revision = 'b15baf06017b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
