"""version 16

Revision ID: d118ea41ae05
Revises: a8c071ab6076
Create Date: 2021-02-15 10:37:36.038828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd118ea41ae05'
down_revision = 'a8c071ab6076'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
