"""version 13

Revision ID: d1d3a355711b
Revises: 926cab5a55e2
Create Date: 2021-02-08 09:37:05.219494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1d3a355711b'
down_revision = '926cab5a55e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
