"""version 14

Revision ID: daa6a6107e43
Revises: b81465f8e210
Create Date: 2021-02-08 09:39:15.365496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daa6a6107e43'
down_revision = 'b81465f8e210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
