"""version 11

Revision ID: db131287c30e
Revises: 9d92e4372813
Create Date: 2021-02-08 09:26:25.575125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db131287c30e'
down_revision = '9d92e4372813'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diecuts', sa.Column('col_test1', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diecuts', 'col_test1')
    # ### end Alembic commands ###
