"""version 21

Revision ID: df4caffb8bbf
Revises: bb96342dcba7
Create Date: 2021-03-04 15:48:24.109780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df4caffb8bbf'
down_revision = 'bb96342dcba7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
