"""version 19

Revision ID: 3eedea736abb
Revises: 9ffcd85fbe9f
Create Date: 2021-02-15 13:25:10.065326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eedea736abb'
down_revision = '9ffcd85fbe9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
