"""version 4

Revision ID: 6cbeabbaa6fd
Revises: f30b2204768b
Create Date: 2021-02-04 14:34:55.872111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cbeabbaa6fd'
down_revision = 'f30b2204768b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diecuts', sa.Column('descriptions', sa.Text(), nullable=True))
    op.add_column('diecuts', sa.Column('img', sa.String(length=255), nullable=True))
    op.add_column('diecuts', sa.Column('slug', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diecuts', 'slug')
    op.drop_column('diecuts', 'img')
    op.drop_column('diecuts', 'descriptions')
    # ### end Alembic commands ###
