"""version 9

Revision ID: 8f5a28c813ec
Revises: 0a38d2ccd074
Create Date: 2021-02-08 08:11:34.591041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f5a28c813ec'
down_revision = '0a38d2ccd074'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
