"""version 4

Revision ID: aa30e1f30450
Revises: 6cbeabbaa6fd
Create Date: 2021-02-04 14:35:48.812618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa30e1f30450'
down_revision = '6cbeabbaa6fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diecuts', 'slug')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diecuts', sa.Column('slug', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
