"""version 01

Revision ID: c89afba0741a
Revises: 5b90e753cec5
Create Date: 2021-03-29 15:06:50.004229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c89afba0741a'
down_revision = '5b90e753cec5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('digital_jobs_print', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'digital_jobs_print', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'digital_jobs_print', type_='foreignkey')
    op.drop_column('digital_jobs_print', 'customer_id')
    # ### end Alembic commands ###
