"""version 01

Revision ID: d5294f28afb6
Revises: 9e949e327084
Create Date: 2021-03-30 15:42:38.837471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5294f28afb6'
down_revision = '9e949e327084'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('digitaljob_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'customers', 'digital_jobs_print', ['digitaljob_id'], ['digitaljob_id'])
    op.drop_constraint('digital_jobs_print_customer_id_fkey', 'digital_jobs_print', type_='foreignkey')
    op.drop_column('digital_jobs_print', 'customer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('digital_jobs_print', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('digital_jobs_print_customer_id_fkey', 'digital_jobs_print', 'customers', ['customer_id'], ['id'])
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_column('customers', 'digitaljob_id')
    # ### end Alembic commands ###
