"""version 17

Revision ID: e5845b9caf70
Revises: d118ea41ae05
Create Date: 2021-02-15 10:38:46.450949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5845b9caf70'
down_revision = 'd118ea41ae05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
