"""version 3

Revision ID: f30b2204768b
Revises: 91d1ea1b3660
Create Date: 2021-02-04 13:58:23.605336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f30b2204768b'
down_revision = '91d1ea1b3660'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.add_column('diecuts', sa.Column('cf2', sa.String(length=255), nullable=True))
    op.add_column('diecuts', sa.Column('hcountitem', sa.Integer(), nullable=False))
    op.add_column('diecuts', sa.Column('hgap', sa.DECIMAL(precision=10, scale=4), nullable=False))
    op.add_column('diecuts', sa.Column('mfg', sa.String(length=255), nullable=True))
    op.add_column('diecuts', sa.Column('slug', sa.String(length=50), nullable=True))
    op.add_column('diecuts', sa.Column('vcountitem', sa.Integer(), nullable=False))
    op.add_column('diecuts', sa.Column('vgap', sa.DECIMAL(precision=10, scale=4), nullable=False))
    op.add_column('diecuts', sa.Column('vsheet', sa.Integer(), nullable=False))
    op.add_column('diecuts', sa.Column('zub_num', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'diecuts', 'zubs', ['zub_num'], ['zub_num'])
    op.add_column('zubs', sa.Column('hpolimer', sa.DECIMAL(precision=10, scale=4), nullable=False))
    op.add_column('zubs', sa.Column('hpolimer_17', sa.DECIMAL(precision=10, scale=4), nullable=False))
    op.add_column('zubs', sa.Column('hprint', sa.DECIMAL(precision=10, scale=4), nullable=False))
    op.create_unique_constraint(None, 'zubs', ['hpolimer_17'])
    op.create_unique_constraint(None, 'zubs', ['hprint'])
    op.create_unique_constraint(None, 'zubs', ['zub_num'])
    op.create_unique_constraint(None, 'zubs', ['hpolimer'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'zubs', type_='unique')
    op.drop_constraint(None, 'zubs', type_='unique')
    op.drop_constraint(None, 'zubs', type_='unique')
    op.drop_constraint(None, 'zubs', type_='unique')
    op.drop_column('zubs', 'hprint')
    op.drop_column('zubs', 'hpolimer_17')
    op.drop_column('zubs', 'hpolimer')
    op.drop_constraint(None, 'diecuts', type_='foreignkey')
    op.drop_column('diecuts', 'zub_num')
    op.drop_column('diecuts', 'vsheet')
    op.drop_column('diecuts', 'vgap')
    op.drop_column('diecuts', 'vcountitem')
    op.drop_column('diecuts', 'slug')
    op.drop_column('diecuts', 'mfg')
    op.drop_column('diecuts', 'hgap')
    op.drop_column('diecuts', 'hcountitem')
    op.drop_column('diecuts', 'cf2')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
